package oklab

import (
	"math"
	"testing"
)

// Reference pairs generated by the Python palette service's own conversion.
// The two implementations sit on opposite sides of an HTTP boundary and must
// agree about what a colour is, so this checks the Go inverse transform
// against the Python one rather than against itself.
var pythonReference = []struct {
	lab  Lab
	want RGB
}{
	{Lab{L: 0.625004, A: 0.146875, B: 0.118273}, RGB{R: 225, G: 82, B: 26}},
	{Lab{L: 0.532009, A: 0.179471, B: 0.076480}, RGB{R: 196, G: 34, B: 49}},
	{Lab{L: 0.449257, A: -0.036360, B: -0.116234}, RGB{R: 22, G: 86, B: 150}},
	{Lab{L: 0.803761, A: 0.017498, B: 0.160967}, RGB{R: 240, G: 180, B: 20}},
	{Lab{L: 0.540693, A: -0.103657, B: 0.035086}, RGB{R: 30, G: 130, B: 90}},
	{Lab{L: 0.536037, A: 0.001549, B: 0.021077}, RGB{R: 115, G: 109, B: 96}},
	{Lab{L: 0.000000, A: 0.000000, B: 0.000000}, RGB{R: 0, G: 0, B: 0}},
	{Lab{L: 1.000000, A: 0.000000, B: 0.000000}, RGB{R: 255, G: 255, B: 255}},
}

func TestMatchesPythonImplementation(t *testing.T) {
	for _, tc := range pythonReference {
		got := tc.lab.ToSRGB()
		if diff(got.R, tc.want.R) > 1 || diff(got.G, tc.want.G) > 1 || diff(got.B, tc.want.B) > 1 {
			t.Errorf("ToSRGB(%v) = %v, python says %v", tc.lab, got, tc.want)
		}
	}
}

func TestChroma(t *testing.T) {
	if c := (Lab{L: 0.5}).Chroma(); c != 0 {
		t.Errorf("neutral chroma = %v, want 0", c)
	}
	if c := (Lab{L: 0.5, A: 0.3, B: 0.4}).Chroma(); math.Abs(c-0.5) > 1e-9 {
		t.Errorf("chroma = %v, want 0.5", c)
	}
}

func TestScaleChromaKeepsHueAndLightness(t *testing.T) {
	base := Lab{L: 0.55, A: 0.10, B: 0.05}
	scaled := base.ScaleChroma(1.5)

	if scaled.L != base.L {
		t.Errorf("lightness moved: %v -> %v", base.L, scaled.L)
	}
	// Hue is the angle of (A, B); scaling both preserves it exactly.
	if math.Abs(math.Atan2(scaled.B, scaled.A)-math.Atan2(base.B, base.A)) > 1e-12 {
		t.Error("hue angle moved under chroma scaling")
	}
	if scaled.Chroma() <= base.Chroma() {
		t.Error("chroma did not increase")
	}
}

// The reason for walking chroma down instead of clipping channels: clipping a
// blown channel while leaving the others alone shifts hue, so a boosted colour
// arrives as a different colour than the one on the sleeve.
func TestOutOfGamutPreservesHue(t *testing.T) {
	// A saturated orange pushed well past what sRGB can represent.
	base := Lab{L: 0.625, A: 0.147, B: 0.118}
	boosted := base.ScaleChroma(3.0)

	got := boosted.ToSRGB()
	inGamut := base.ScaleChroma(3.0).toLinear().inGamut()
	if inGamut {
		t.Fatal("test premise broken: colour is not actually out of gamut")
	}

	// The recovered colour must still read as orange: red highest, blue lowest.
	if !(got.R > got.G && got.G > got.B) {
		t.Errorf("hue order broken under gamut mapping: %v", got)
	}
	if got.R < 200 {
		t.Errorf("gamut mapping dimmed the colour too far: %v", got)
	}
}

func TestGamutMappedResultIsRepresentable(t *testing.T) {
	for _, k := range []float64{1, 1.5, 2, 4, 8} {
		lab := Lab{L: 0.45, A: -0.036, B: -0.116}.ScaleChroma(k)
		got := lab.ToSRGB()
		// Every channel is a uint8 by construction; the real assertion is that
		// nothing wrapped or saturated to a flat 0/255 triple.
		if got.R == 255 && got.G == 255 && got.B == 255 {
			t.Errorf("k=%v collapsed to white", k)
		}
	}
}

func diff(a, b uint8) int {
	if a > b {
		return int(a - b)
	}
	return int(b - a)
}
